version: '3.8'
services:
  frontend:
    build: ./nba-stats-server
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./nba-stats-frontend
    ports:
      - "5000:5000"
